name: Generate Snake

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: seakyy
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git diff --staged --quiet || git commit -m "Update snake animation"
          git push
